apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubernetes-demo-app
  template:
    metadata:
      labels:
        app: kubernetes-demo-app
    spec:
      containers:
        - name: kubernetes-demo-app
          image: jineshjain123/kubernetes-demo-1:v1
          volumeMounts:
            - mountPath: /app/upload
              name : myvolume
      volumes:
        - name : myvolume
          persistentVolumeClaim:
            claimName: mypvc


