apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
spec:
  hostPath: 
    path: /data
    type: DirectoryOrCreate
  capacity:
    storage: 4Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
