apiVersion: v1
kind: Service
metadata:
  name: kubernetes-demo
spec:
  selector:
    app: kubernetes-demo-app
  ports:
    - port: 8000
      targetPort: 8000
      protocol: 'TCP'
  type: LoadBalancer
